In [ ]:
import numpy as np

### Classe para o problema

In [ ]:
class SlidingPuzzle:
  def __init__(self, num_blocos):
    self.num_blocos = num_blocos

  def _encontra_posicao(self, estado, elemento):
    for i in range(self.num_blocos):
      for j in range(self.num_blocos):
        if elemento == estado[i, j]:
          return i, j
    return None, None

  def verifica_estados(self, atual, objetivo):
    for i in range(self.num_blocos):
      for j in range(self.num_blocos):
        if atual[i, j] != objetivo[i, j]:
          return False
    return True

  def expande_estados(self, atual):
    novos_estados = []

    linha, coluna = self._encontra_posicao(atual, 0)

    # Cima
    if linha > 0:
      nova_linha = linha - 1
      novo_estado = np.copy(atual)

      bloco_alvo = atual[nova_linha, coluna]
      novo_estado[nova_linha, coluna] = 0
      novo_estado[linha, coluna] = bloco_alvo
      novos_estados.append(novo_estado)

    # Baixo
    if linha < self.num_blocos - 1:
      nova_linha = linha + 1
      novo_estado = np.copy(atual)

      bloco_alvo = atual[nova_linha, coluna]
      novo_estado[nova_linha, coluna] = 0
      novo_estado[linha, coluna] = bloco_alvo
      novos_estados.append(novo_estado)

    # Esquerda
    if coluna > 0:
      nova_coluna = coluna - 1
      novo_estado = np.copy(atual)

      bloco_alvo = atual[linha, nova_coluna]
      novo_estado[linha, nova_coluna] = 0
      novo_estado[linha, coluna] = bloco_alvo
      novos_estados.append(novo_estado)

    # Direita
    if coluna < self.num_blocos - 1:
      nova_coluna = coluna + 1
      novo_estado = np.copy(atual)

      bloco_alvo = atual[linha, nova_coluna]
      novo_estado[linha, nova_coluna] = 0
      novo_estado[linha, coluna] = bloco_alvo
      novos_estados.append(novo_estado)

    return novos_estados

### Classe para a busca

In [ ]:
from queue import Queue

In [ ]:
class BreadthFirstSearch:
  def __init__(self, problema):
    self.problema = problema
  
  def _verifica_visitados(self, estado, estados_visitados):
    for i in estados_visitados:
      if self.problema.verifica_estados(i, estado):
        return True
    return False

  def busca(self, inicio, fim):
    fila = Queue()
    fila.put(inicio)

    solucao_encontrada = False
    estados_visitados = []
    cont_estados = 0

    while not fila.empty():
      atual = fila.get()

      estados_visitados.append(atual)

      if self.problema.verifica_estados(atual, fim):
        solucao_encontrada = True
        break
      else:
        cont_estados += 1
        print("Visitando estado", cont_estados)

        novos_estados = self.problema.expande_estados(atual)
        for i in novos_estados:
          if not self._verifica_visitados(i, estados_visitados):
            fila.put(i)

    return solucao_encontrada, estados_visitados, cont_estados
          

### Main

In [ ]:
start = np.matrix([[2, 8, 3], [1, 6, 4], [7, 0, 5]])
target = np.matrix([[1, 2, 3], [8, 0, 4], [7, 6, 5]])

In [ ]:
problema = SlidingPuzzle(3)
bfs = BreadthFirstSearch(problema)

In [ ]:
solucao, visitados, passos = bfs.busca(start, target)

if solucao:
  print("Solução encontrada com", passos)
else:
  print("Solução não foi encontrada")

Visitando estado 1
[[2 8 3]
 [1 0 4]
 [7 6 5]]
[[2 8 3]
 [1 6 4]
 [0 7 5]]
[[2 8 3]
 [1 6 4]
 [7 5 0]]
Visitando estado 2
[[2 0 3]
 [1 8 4]
 [7 6 5]]
[[2 8 3]
 [0 1 4]
 [7 6 5]]
[[2 8 3]
 [1 4 0]
 [7 6 5]]
Visitando estado 3
[[2 8 3]
 [0 6 4]
 [1 7 5]]
Visitando estado 4
[[2 8 3]
 [1 6 0]
 [7 5 4]]
Visitando estado 5
[[0 2 3]
 [1 8 4]
 [7 6 5]]
[[2 3 0]
 [1 8 4]
 [7 6 5]]
Visitando estado 6
[[0 8 3]
 [2 1 4]
 [7 6 5]]
[[2 8 3]
 [7 1 4]
 [0 6 5]]
Visitando estado 7
[[2 8 0]
 [1 4 3]
 [7 6 5]]
[[2 8 3]
 [1 4 5]
 [7 6 0]]
Visitando estado 8
[[0 8 3]
 [2 6 4]
 [1 7 5]]
[[2 8 3]
 [6 0 4]
 [1 7 5]]
Visitando estado 9
[[2 8 0]
 [1 6 3]
 [7 5 4]]
[[2 8 3]
 [1 0 6]
 [7 5 4]]
Visitando estado 10
[[1 2 3]
 [0 8 4]
 [7 6 5]]
Visitando estado 11
[[2 3 4]
 [1 8 0]
 [7 6 5]]
Visitando estado 12
[[8 0 3]
 [2 1 4]
 [7 6 5]]
Visitando estado 13
[[2 8 3]
 [7 1 4]
 [6 0 5]]
Visitando estado 14
[[2 0 8]
 [1 4 3]
 [7 6 5]]
Visitando estado 15
[[2 8 3]
 [1 4 5]
 [7 0 6]]
Visitando estado 16
[[8 0 3]
 [2 6 4]